# 调度的时间时间间隔以及立即重试次数
trigger:
  schedule:
    time: 1000
  retry:
    count: 3

# 定时重试
retry:
  run:
    job:
      schedule:
        time: 300
  call:
    error:
      job:
        schedule:
          time: 600
        count:
          threshold: 10

# 定时删除 remove = 1 的任务
delete:
  job:
    schedule:
      time: 600
