server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.67.37.210:3306/mytrigger
    username: root
    password: Nsf0cus!@

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.onedawn.mytrigger.triggercenter.dao.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  config: classpath:logback-spring.xml
  file:
    path: D:/logs/my-trigger


# 调度的时间时间间隔以及立即重试次数
trigger:
  schedule:
    time: 1000
  retry:
    count: 3
# 定时重试
retry:
  run:
    job:
      schedule:
        time: 300
  call:
    error:
      job:
        schedule:
          time: 600
        count:
          threshold: 10
# 定时删除 remove = 1 的任务
delete:
  job:
    schedule:
      time: 600
