server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.4:3306/mytrigger
    username: mytrigger
    password: mytrigger
    hikari:
      connection-timeout=30000
      maximum-pool-size=50
      minimum-idle=3
      idle-timeout=600000
      pool-name=my-pool

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.onedawn.mytrigger.triggercenter.dao.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    cache-enabled: true
    jdbc-type-for-null: null
    auto-mapping-behavior: full

logging:
  config: classpath:logback-spring.xml
  file:
    path: D:/logs/my-trigger

elasticsearch:
  host: 192.168.5.4
  port: 9200
  index:
    name: 'my-trigger'

# 调度的时间时间间隔以及立即重试次数
trigger:
  schedule:
    time: 1000
  retry:
    count: 3
# 定时重试
retry:
  run:
    job:
      schedule:
        time: 300
  call:
    error:
      job:
        schedule:
          time: 600
        count:
          threshold: 10
# 定时删除 remove = 1 的任务
delete:
  job:
    schedule:
      time: 600
